version: 2

jobs:
  build:
    //node:
    //  version: 0.10
    //machine: true
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run:
          name: Testing
          command: ./node_modules/.bin/mocha
