version: 2

jobs:
  build:
    //node:
    //  version: 0.10
    //machine: true
    machine:
      image: circleci/node:4.8.2-jessie
    steps:
      - run:
          name: Testing
          command: ./node_modules/.bin/mocha
