version: 2

jobs:
  build:
    node:
      - version: 0.10
    //machine: true
    machine:
      image: node
    steps:
      - run:
          name: Testing
          command: ./node_modules/.bin/mocha
