version: 2

jobs:
  build:
    //node:
    //  version: 0.10
    machine:
      - node:
          version: 0.10
    steps:
      - run:
          name: Testing
          command: ./node_modules/.bin/mocha
